name: "Stack Parameters"
description:
  "Retrieve CloudFormation stack outputs and amend parameters for deployment"
author: "copilot-ld"

inputs:
  retrieve:
    description: "JSON object mapping stack names to output keys to retrieve"
    required: false
    default: ""
  amend:
    description: "JSON object with key-value pairs to amend to parameters"
    required: false
    default: ""
  output-file:
    description: "Output file path for parameters (default: parameters.json)"
    required: false
    default: "parameters.json"
  aws-region:
    description: "AWS region for CloudFormation operations"
    required: false
    default: "us-east-1"

outputs:
  parameters-file:
    description: "Path to the generated parameters file"
    value: ${{ steps.process.outputs.parameters-file }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        npm ci

    - name: Process stack parameters
      id: process
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        RETRIEVE_INPUT: ${{ inputs.retrieve }}
        AMEND_INPUT: ${{ inputs.amend }}
        OUTPUT_FILE: ${{ inputs.output-file }}
      run: |
        cd $GITHUB_WORKSPACE

        if [ -n "$RETRIEVE_INPUT" ]; then
          echo "$RETRIEVE_INPUT" | npx --workspace=@copilot-ld/librel rel-parameters --retrieve --file="$OUTPUT_FILE"
        fi

        if [ -n "$AMEND_INPUT" ]; then
          echo "$AMEND_INPUT" | npx --workspace=@copilot-ld/librel rel-parameters --amend --file="$OUTPUT_FILE"
        fi

        echo "parameters-file=$(pwd)/$OUTPUT_FILE" >> $GITHUB_OUTPUT
