name: "Setup Node.js"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        registry-url: "https://npm.pkg.github.com"
        scope: "@copilot-ld"
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Generate code
      shell: bash
      run: npm run codegen
