name: "Setup"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm"
        registry-url: "https://npm.pkg.github.com"

    - name: Cache apt packages
      uses: actions/cache@v4
      with:
        path: ~/apt-cache
        key:
          ${{ runner.os }}-apt-${{
          hashFiles('.github/actions/setup-node/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    # This dependency is needed for libtransform
    - name: Install pdftoppm
      shell: bash
      run: |
        mkdir -p ~/apt-cache
        sudo apt-get update
        sudo apt-get install -y -d -o Dir::Cache::Archives="$HOME/apt-cache" poppler-utils
        sudo apt-get install -y -o Dir::Cache::Archives="$HOME/apt-cache" poppler-utils
        sudo chown -R $USER ~/apt-cache

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-tei-${{ hashFiles('.github/actions/setup-node/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-tei-

    - name: Install TEI
      shell: bash
      run: |
        if ! command -v text-embeddings-router &> /dev/null; then
          make tei-install
        fi

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts

    - name: Generate code
      shell: bash
      run: |
        make data-init
        make codegen
