tool:
  download:
    owner: "some-github-owner"
    repo: "some-github-repo"

# Storage configuration (optional - defaults to local filesystem)
# Uncomment and configure for S3-compatible storage (e.g., MinIO)
#storage: s3
#s3_endpoint: http://localhost:9000
#s3_region: us-east-1
#s3_bucket: copilot-ld
#s3_access_key_id: minioadmin
#s3_secret_access_key: minioadmin

service:
  agent:
    threshold: 0.3
    limit: 50
    temperature: 0.2
    systemInstructionsTokens: 1000
    historyTokens: 2000
    similaritySearchTokens: 3000
    prompts:
      - "You help with software development practices."
      - "Keep your introduction brief and focused on the task."
      - "Format your responses in Markdown, using code blocks when relevant."

  history:
    ttl: 3600
    checkperiod: 600
    historyTokens: 4000

  llm:
    model: "claude-3.5-sonnet"
