AWSTemplateFormatVersion: "2010-09-09"
Description:
  "Extensions stack for Copilot-LD platform - Web extension and ALB routing"

Parameters:
  EnvironmentName:
    Type: String
    Default: copilot-ld-demo
    Description: Environment name for resource naming

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for deployment

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: Private subnets for web extension (minimum two)

  ServiceSecurityGroupId:
    Type: String
    Description: Security group ID for services

  ALBListenerArn:
    Type: String
    Description: ARN of the ALB HTTP listener

  ServiceDiscoveryNamespaceId:
    Type: String
    Description: Service discovery namespace ID

  ContainerTag:
    Type: String
    Default: latest
    Description: Container image tag

  RegistryUrl:
    Type: String
    Description: ECR registry URL from registry stack

  # LLM secrets
  LlmTokenArn:
    Type: String
    Description: ARN of the LLM token secret in AWS Secrets Manager

  LlmBaseUrlArn:
    Type: String
    Description: ARN of the LLM base URL secret in AWS Secrets Manager

  # JWT secrets
  JwtSecretArn:
    Type: String
    Description: ARN of the JWT signing secret in AWS Secrets Manager

  JwtAnonKeyArn:
    Type: String
    Description: ARN of the JWT anonymous key secret in AWS Secrets Manager

  # Service secrets
  ServiceSecretArn:
    Type: String
    Description: ARN of the service authentication secret in AWS Secrets Manager

  DatabasePasswordArn:
    Type: String
    Description: ARN of the database password secret in AWS Secrets Manager

  BucketName:
    Type: String
    Description: S3 bucket name for all data storage

  BucketRoleArn:
    Type: String
    Description: IAM role ARN for data access services

  SecretsRoleArn:
    Type: String
    Description: IAM role ARN for secrets access services

Resources:
  # ==========================================
  # ECS INFRASTRUCTURE
  # ==========================================

  # ECS cluster for hosting extension services
  ExtensionsCluster:
    Type: AWS::ECS::Cluster

  # ==========================================
  # ALB TARGET GROUP AND ROUTING
  # ==========================================

  # Target group for web extension load balancer routing
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 3000
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /web/health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"

  # Target group for ui extension load balancer routing
  UiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 3000
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /ui/health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"

  # Listener rule for web extension
  WebListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref WebTargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - "/web/*"
      ListenerArn: !Ref ALBListenerArn
      Priority: 100

  # Listener rule for ui extension
  UiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref UiTargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - "/ui/*"
      ListenerArn: !Ref ALBListenerArn
      Priority: 110

  # ==========================================
  # LOGGING
  # ==========================================

  # CloudWatch log group for web extension logging
  WebLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  # CloudWatch log group for ui extension logging
  UiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  # ==========================================
  # TASK DEFINITION
  # ==========================================

  # ECS task definition for web extension container
  WebTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref SecretsRoleArn
      TaskRoleArn: !Ref BucketRoleArn
      ContainerDefinitions:
        - Name: web
          Image: !Sub "${RegistryUrl}/${EnvironmentName}/web:${ContainerTag}"
          Essential: true
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: STORAGE_TYPE
              Value: s3
            - Name: S3_BUCKET_NAME
              Value: !Ref BucketName
            - Name: DEBUG
              Value: "*"
          Secrets:
            # LLM secrets
            - Name: LLM_TOKEN
              ValueFrom: !Sub "${LlmTokenArn}:LLM_TOKEN::"
            - Name: LLM_BASE_URL
              ValueFrom: !Sub "${LlmBaseUrlArn}:LLM_BASE_URL::"
            # JWT secrets
            - Name: JWT_SECRET
              ValueFrom: !Sub "${JwtSecretArn}:JWT_SECRET::"
            - Name: JWT_ANON_KEY
              ValueFrom: !Sub "${JwtAnonKeyArn}:JWT_ANON_KEY::"
            # Service secrets
            - Name: SERVICE_SECRET
              ValueFrom: !Sub "${ServiceSecretArn}:SERVICE_SECRET::"
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub "${DatabasePasswordArn}:DATABASE_PASSWORD::"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref WebLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: web

  # ECS task definition for ui extension container
  UiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref SecretsRoleArn
      TaskRoleArn: !Ref BucketRoleArn
      ContainerDefinitions:
        - Name: ui
          Image: !Sub "${RegistryUrl}/${EnvironmentName}/ui:${ContainerTag}"
          Essential: true
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: STORAGE_TYPE
              Value: s3
            - Name: S3_BUCKET_NAME
              Value: !Ref BucketName
            - Name: DEBUG
              Value: "*"
          Secrets:
            # LLM secrets
            - Name: LLM_TOKEN
              ValueFrom: !Sub "${LlmTokenArn}:LLM_TOKEN::"
            - Name: LLM_BASE_URL
              ValueFrom: !Sub "${LlmBaseUrlArn}:LLM_BASE_URL::"
            # JWT secrets
            - Name: JWT_SECRET
              ValueFrom: !Sub "${JwtSecretArn}:JWT_SECRET::"
            - Name: JWT_ANON_KEY
              ValueFrom: !Sub "${JwtAnonKeyArn}:JWT_ANON_KEY::"
            # Service secrets
            - Name: SERVICE_SECRET
              ValueFrom: !Sub "${ServiceSecretArn}:SERVICE_SECRET::"
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub "${DatabasePasswordArn}:DATABASE_PASSWORD::"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref UiLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ui

  # ==========================================
  # ECS SERVICE
  # ==========================================

  # ECS service for running web extension container
  WebService:
    Type: AWS::ECS::Service
    DependsOn: WebListenerRule
    Properties:
      Cluster: !Ref ExtensionsCluster
      TaskDefinition: !Ref WebTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ServiceSecurityGroupId
          Subnets: !Ref PrivateSubnetIds
      LoadBalancers:
        - ContainerName: web
          ContainerPort: 3000
          TargetGroupArn: !Ref WebTargetGroup

  # ECS service for running ui extension container
  UiService:
    Type: AWS::ECS::Service
    DependsOn: UiListenerRule
    Properties:
      Cluster: !Ref ExtensionsCluster
      TaskDefinition: !Ref UiTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ServiceSecurityGroupId
          Subnets: !Ref PrivateSubnetIds
      LoadBalancers:
        - ContainerName: ui
          ContainerPort: 3000
          TargetGroupArn: !Ref UiTargetGroup

Outputs:
  ExtensionsClusterName:
    Description: Name of the extensions ECS cluster
    Value: !Ref ExtensionsCluster

  ExtensionsClusterArn:
    Description: ARN of the extensions ECS cluster
    Value: !GetAtt ExtensionsCluster.Arn

  WebServiceArn:
    Description: ARN of the web service
    Value: !Ref WebService

  WebTargetGroupArn:
    Description: ARN of the web target group
    Value: !Ref WebTargetGroup

  UiServiceArn:
    Description: ARN of the ui service
    Value: !Ref UiService

  UiTargetGroupArn:
    Description: ARN of the ui target group
    Value: !Ref UiTargetGroup
