AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR container registry infrastructure for Copilot-LD platform"

Parameters:
  EnvironmentName:
    Type: String
    Default: copilot-ld-demo
    Description: Environment name for resource naming

# YAML anchor for shared lifecycle policy
x-lifecycle-policy: &lifecycle-policy
  LifecyclePolicy:
    LifecyclePolicyText: |
      {
        "rules": [
          {
            "rulePriority": 1,
            "description": "Keep last 10 images",
            "selection": {
              "tagStatus": "any",
              "countType": "imageCountMoreThan",
              "countNumber": 10
            },
            "action": {
              "type": "expire"
            }
          }
        ]
      }

Resources:
  # ==========================================
  # ECR REPOSITORIES FOR SERVICES
  # ==========================================

  AgentRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/agent"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

  MemoryRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/memory"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

  LLMRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/llm"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

  VectorRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/vector"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

  GraphRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/graph"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

  ToolRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/tool"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

  # ==========================================
  # ECR REPOSITORIES FOR EXTENSIONS
  # ==========================================

  WebRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/web"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

  # ==========================================
  # ECR REPOSITORIES FOR INFRASTRUCTURE
  # ==========================================

  GatewayRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/gateway"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

  ALBRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentName}/alb"
      ImageScanningConfiguration:
        ScanOnPush: true
      <<: *lifecycle-policy

Outputs:
  RegistryUrl:
    Description: ECR registry URL
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com"

  AgentRepositoryUri:
    Description: ECR repository URI for agent service
    Value: !GetAtt AgentRepository.RepositoryUri

  MemoryRepositoryUri:
    Description: ECR repository URI for memory service
    Value: !GetAtt MemoryRepository.RepositoryUri

  LLMRepositoryUri:
    Description: ECR repository URI for LLM service
    Value: !GetAtt LLMRepository.RepositoryUri

  VectorRepositoryUri:
    Description: ECR repository URI for vector service
    Value: !GetAtt VectorRepository.RepositoryUri

  GraphRepositoryUri:
    Description: ECR repository URI for graph service
    Value: !GetAtt GraphRepository.RepositoryUri

  ToolRepositoryUri:
    Description: ECR repository URI for tool service
    Value: !GetAtt ToolRepository.RepositoryUri

  WebRepositoryUri:
    Description: ECR repository URI for web extension
    Value: !GetAtt WebRepository.RepositoryUri

  GatewayRepositoryUri:
    Description: ECR repository URI for gateway infrastructure
    Value: !GetAtt GatewayRepository.RepositoryUri

  ALBRepositoryUri:
    Description: ECR repository URI for ALB infrastructure
    Value: !GetAtt ALBRepository.RepositoryUri
