AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Secrets Manager secrets for Copilot-LD platform"

Parameters:
  EnvironmentName:
    Type: String
    Default: copilot-ld-demo
    Description: Environment name for resource naming

  LlmTokenValue:
    Type: String
    NoEcho: true
    Description: LLM API token for API access

  ServiceSecretValue:
    Type: String
    NoEcho: true
    Description: Service authentication secret

Resources:
  # LLM token secret for API access
  LlmToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: LLM API token for Copilot-LD API access
      SecretString: !Sub |
        {
          "LLM_TOKEN": "${LlmTokenValue}"
        }
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  # Service secret for inter-service communication
  ServiceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description:
        Service authentication secret for Copilot-LD inter-service communication
      SecretString: !Sub |
        {
          "SERVICE_SECRET": "${ServiceSecretValue}"
        }
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  # IAM role for ECS tasks to access secrets
  SecretsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref LlmToken
                  - !Ref ServiceSecret

Outputs:
  LlmTokenArn:
    Description: ARN of the LLM token secret
    Value: !Ref LlmToken

  ServiceSecretArn:
    Description: ARN of the service secret
    Value: !Ref ServiceSecret

  SecretsRoleArn:
    Description: IAM role ARN for accessing secrets
    Value: !GetAtt SecretsRole.Arn
