tool:
  download:
    owner: "some-github-owner"
    repo: "some-github-repo"

service:
  agent:
    threshold: 0.25
    limit: 100
    temperature: 0.25
    budget:
      tokens: 90000
      allocation:
        tools: 0.1
        history: 0.1
        context: 0.6
    assistant: "cld:common.Assistant.software-dev-expert"

  history:
    ttl: 3600
    checkperiod: 600
    historyTokens: 4000

  llm:
    model: "claude-3.5-sonnet"
