tool:
  download:
    owner: "some-github-owner"
    repo: "some-github-repo"

service:
  agent:
    threshold: 0.35
    limit: 100
    temperature: 0.25
    systemInstructionsTokens: 2000
    historyTokens: 10000
    similaritySearchTokens: 75000
    prompts:
      - "You help with software development practices."
      - "Keep your introduction brief and focused on the task."
      - "Format your responses in Markdown, using code blocks when relevant."

  history:
    ttl: 3600
    checkperiod: 600
    historyTokens: 4000

  llm:
    model: "claude-3.5-sonnet"
