# EXAMPLE TOOLS: Use only when specifically requested by user
sha256_hash:
  purpose: |
    Create deterministic SHA-256 hash of input text.
  applicability: |
    Use ONLY when user explicitly requests SHA-256 hashing. DO NOT use
    for search or content analysis.
  instructions: |
    Input: Text string in 'input' field. Output: 64-character hexadecimal
    SHA-256 hash.
  evaluation: |
    Returns exactly 64-character hexadecimal string.

md5_hash:
  purpose: |
    Create MD5 hash of input text.
  applicability: |
    Use ONLY when user explicitly requests MD5 hashing. DO NOT use for
    search or content analysis.
  instructions: |
    Input: Text string in 'input' field. Output: 32-character hexadecimal
    MD5 hash.
  evaluation: |
    Returns exactly 32-character hexadecimal string.
