name: Demo Storage Deployment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Environment name prefix for resources"
        required: true
        default: "demo"
        type: string

jobs:
  deploy-storage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEMO_AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy
        run: |
          STACK_NAME="${{ inputs.environment_name }}-cld-data-stack-cf"
          aws cloudformation deploy \
            --template-file infrastructure/cloudformation/storage.yml \
            --stack-name $STACK_NAME \
            --parameter-overrides \
              EnvironmentName=${{ inputs.environment_name }} \
            --capabilities CAPABILITY_IAM \
            --region us-east-1
